### PR TITLE
fix for install without changing name

### PR DESCRIPTION
**Pull request by gavinwade12**
This is a simple fix. However, it is untested and my first PR was my first stab at Ruby. Please test this if you are going to pull. When I get home from work I can test if you haven't already.

### CODE REVIEW

**Comment by Sprinting** [comment]
@gavinwade12  I would, but I don't know anything about ruby, yet. I can't imagine my tests would be anyuse
@xeon-zolt  look at this

**Comment by gavinwade12** [comment]
I just tested this on my mac. Easy fix. I had just accidentally used a constant instead of an instance variable.

**Comment by xeon-zolt** [comment]
tested and its working on my arch machine too

**Comment by xeon-zolt** [comment]
but its only changing the name in statements not the command used to call it

**Comment by gavinwade12** [comment]
The issue with that is you must source your bash profile so your shell can see the changes (e.g. `source ~/.bash_profile`). I'll see if I can add that to the script.

**Pull request merged**
