### PR TITLE
Make Betty easier to start with

### PR DESCRIPTION
**Pull request by tessi**
Attempt to help with #1
- enhance betty's response when there are no arguments.
- give her a help message which lists all available categories.

screen shot 2016-10-15 at 19 10 06

### CODE REVIEW

**Comment by xeon-zolt** [comment]
Nice idea , i was thinking we should arrange them in multiple columns so that it dont get messy when more stuff is added
Thanks @tessi

**Review by xeon-zolt — APPROVED** [review]

**Comment by tessi** [comment]
Nice idea to arrange the answer in columns. Not sure yet how to do this. I'll think about it :)

**Comment by xeon-zolt** [comment]
screenshot from 2016-10-16 01-40-40
@tessi Issue here

**Comment by tessi** [comment]
hmm, could it be zsh interpreting the question mark somehow?

Try to remove the `?` from the regex, does it work then?

**Comment by xeon-zolt** [comment]
## After removing   `?`     from Regex    ⬃

peek 2016-10-16 12-49

**Comment by tessi** [comment]
Hmm, it seems we can't ask betty proper questions then. I'll open a PR which removes the question mark. Thanks for figuring it out :)

**Pull request merged**
